#!/bin/bash -e

# Menages a secure device
# Author: Georgi Kovachev
  Version=1.0.6

# This program menages a secure device
# The secure device is used for sensitive information storage
# It utilizes an encrypted filesystem
#

PATH=/bin:/usr/bin
sync
ME=$(basename       -- "$0")			# program name as invoked
SELF=$(readlink -ve -- "$0")			# /absolute/path/program
SELFDIR=$(dirname   "$SELF")			# /absolute/path
SELFNAME=$(basename "$SELF")			# program (true name)


# configuration start -------------------------
config_file=~/.kassandra/${SELFNAME}.conf	# important! /home/user/.pkg/progname.conf









options=''					# global options
log_opts=''					# write options to log file
LOGFILE='/var/log/kassandra/kassandra.log'	# general log file for kassandra utilities
LOGPREFIX='cmd=$cmd es=$es'			# log message prefix
LOGSUFFIX='USER=$USER SUDO_USER=$SUDO_USER'	# log message suffix
VERBOSE=''					# 0 - never, 2 - disable, 7 - enable, 9 - max
EXECUTE=''					# 0 - never, 2 - disable, 7 - enable, 9 - max
# configuration end ===========================

# global variables start ----------------------
es=0						# exit status
cmd=$1						# command

action='use'					# what to do? (default - if no parameter is supplied) TBC
mount_file=''					# contains encrypted file system
mount_point=''					# encrypted file system mount point
fs_type=''					# file system type
fs_opts=''					# file system options
size=''						# entire volume size, ext3 2080K min, others 128K min
name=''						# device name, comment only, string
fs=''						# file_name only





# global variables end ========================


# load general functions
f=${SELFDIR}/lib/functions.sh
[ -f "$f"  -a  -r "$f" ] && . "$f"	|| \
{ echo "$ME: FATAL ERROR: $f cannot be loaded. Aborting." >&2 ; exit 1 ; }

# load required files
# load_libs  lib/encryption-functions.sh
load_libs  ${SELF}-functions.sh  ${SELF}-do-functions.sh

# embeded functions go here

load_libs -f  ${SELF}-dev-functions.sh -- "$@"	# for development purposes

log Load: \$@="$@"				# log load parameters

case "$1" in
	--version)		version	;;	# exits with status 0
	--help | --usage)	usage	;;	# exits with status 0
esac

# must_be_root					# root permissions required - exit if not granted
getoptions "$options" "$@"	&& shift $((OPTIND-1))	|| es=2
init "$@"			|| es=$?

log Init: "$(eval echo "$log_opts")" \$@="$@"	# log decoded parameters

feedback --on-load		|| es=$?
[ $es -eq 0 ]			|| exit $es

# move up to action: do what is needed
sync
case "$cmd" in
	create | mount | umount | use)
		do_$cmd "$@"	|| es=$?
	;;
	*)
		usage 1
	;;
esac
feedback --on-exit

log Exit:					# log exit status

sync
exit $es

